# Generated by Django 4.0 on 2022-01-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0003_alter_citizenuser_amka'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citizenuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='amka',
            field=models.ForeignKey(db_column='amka', on_delete=django.db.models.deletion.DO_NOTHING, to='vaccinationdb.citizen', unique=True),
        ),
    ]
