# Generated by Django 4.0 on 2022-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0004_alter_citizenuser_managers_alter_certificate_amka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vaccination_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
