# Generated by Django 4.0 on 2022-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0005_alter_vaccination_vaccination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
