# Generated by Django 4.0 on 2022-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0007_citizenuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testingspot',
            name='testing_spot_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinationspot',
            name='vax_spot_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
