# Generated by Django 4.0 on 2022-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0008_alter_certificate_certificate_id_and_more'),
    ]

    operations = [

    ]
