# Generated by Django 4.0 on 2022-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationdb', '0009_alter_healthcarestaff_employee_id'),
    ]

    operations = [

    ]
